### ISSUE TITLE
xknx SessionAuthenticate Error Home Assistant 2022.8.1

### ISSUE THREAD

**Issue by stalakerob** [nagyrobi/home-assistant-custom-components-cover-rf-time-based#48]
I am getting the following error during HA startup. I'm using a raspberry pi 4 with Bullseye OS and HA in a docker environment. Until now I never had a problem with this component but suddenly this one popped up. I'm using a MQTT based cover. 

`home-assistant   | 2022-08-06 11:56:09.193 ERROR (MainThread) [homeassistant.components.cover] Error while setting up cover_rf_time_based platform for cover
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
home-assistant   |     await asyncio.shield(task)
home-assistant   |   File "/config/custom_components/cover_rf_time_based/cover.py", line 150, in async_setup_platform
home-assistant   |     async_add_entities(devices_from_config(config))
home-assistant   |   File "/config/custom_components/cover_rf_time_based/cover.py", line 132, in devices_from_config
home-assistant   |     device = CoverTimeBased(device_id,
home-assistant   |   File "/config/custom_components/cover_rf_time_based/cover.py", line 178, in __init__
home-assistant   |     from xknx.devices import TravelCalculator
home-assistant   |   File "/usr/local/lib/python3.10/site-packages/xknx/__init__.py", line 3, in <module>
home-assistant   |     from .xknx import XKNX
home-assistant   |   File "/usr/local/lib/python3.10/site-packages/xknx/xknx.py", line 9, in <module>
home-assistant   |     from xknx.io import ConnectionConfig, KNXIPInterface
home-assistant   |   File "/usr/local/lib/python3.10/site-packages/xknx/io/__init__.py", line 10, in <module>
home-assistant   |     from .request_response import RequestResponse
home-assistant   |   File "/usr/local/lib/python3.10/site-packages/xknx/io/request_response/__init__.py", line 6, in <module>
home-assistant   |     from .authenticate import Authenticate
home-assistant   |   File "/usr/local/lib/python3.10/site-packages/xknx/io/request_response/authenticate.py", line 6, in <module>
home-assistant   |     from xknx.knxip import KNXIPFrame, SessionAuthenticate, SessionStatus
home-assistant   | ImportError: cannot import name 'SessionAuthenticate' from 'xknx.knxip' (/usr/local/lib/python3.10/site-packages/xknx/knxip/__init__.py)
`

**Comment by stalakerob** [comment]
Strange but solved by redownloading the docker image.
